### ISSUE TITLE
关于 本地 Angular Guide 页面 angular 启动问题

### ISSUE THREAD

**Issue by benno233** [jingyanjiaoliu/angular-guide-zh#5]
## 本地 http://localhost:3000/guide 首页代码如下

index.html

<pre>
      addTag('script', {src: path('angular-resource.js') }, sync);
      addTag('script', {src: path('angular-route.js') }, sync);
      addTag('script', {src: path('angular-cookies.js') }, sync);
      addTag('script', {src: path('angular-sanitize.js') }, sync);
      addTag('script', {src: path('angular-touch.js') }, sync);
      addTag('script', {src: path('angular-animate.js') }, sync);
      .......
      addTag('script', {src: 'docs-data.js'}, sync);
      addTag('script', {src: 'js/docs.js'}, sync);
</pre>

这里js 同步加载进来没问题 
## index.html 没有ng-app=docsApp; 而且在 'js/docs.js

<pre>
//也没有手动启动 angular
angular.element().ready(function() {
  
    angular.bootstrap(document, ['docsApp']);
});
</pre>

首页 angular 到底是怎么启动的
请问：我这理解 这到底是哪里不对？

**Comment by why520crazy** [comment]
index.html 的html 标签上有  class="no-js ng-app: docsApp;"  这个和ng-app="docsApp" 是等效的，具体看ng源码中的 angularInit 方法即可

**Comment by benno233** [comment]
好的 谢谢解答
